name: treehmm4glycan-env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - setuptools
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - pip
  - pip:
    - "--editable=git+https://github.com/TreeHMM4Glycan/TreeHMM#egg=tree_hmm"
